"""make_macros.py -- generate results_macros.tex (numbers + GPT table) from real experiment outputs.
Keeps paper/main.tex automatically consistent with results/*.json and runs/*/metrics.jsonl."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
OUT = ROOT / "results_macros.tex"

bench = json.loads((REPO / "results" / "bench.json").read_text())
toy = json.loads((REPO / "results" / "toy.json").read_text())

L = []
L.append("% AUTO-GENERATED by make_macros.py -- do not edit by hand")

# --- operator table macros -------------------------------------------------
ops = [
    ("UniMHC", "UniMHC (Ours)", "unimhc"),
    ("Givens", "GivensMHC (Ours-Fast)", "givens"),
    ("SK", "Sinkhorn mHC (Baseline)", "sinkhorn"),
    ("Ortho", "Orthostochastic (Baseline)", "ortho"),
]
for tag, name, _ in ops:
    p, l = bench["precision"][name], bench["latency"][name]
    t = toy["toy"][name]
    L.append(f"\\newcommand{{\\{tag}RowErr}}{{{p['row_err']:.1e}}}")
    L.append(f"\\newcommand{{\\{tag}ColErr}}{{{p['col_err']:.1e}}}")
    L.append(f"\\newcommand{{\\{tag}IterMs}}{{{l['per_iter_ms']:.2f}}}")
    L.append(f"\\newcommand{{\\{tag}NParams}}{{{p['n_params']}}}")
    L.append(f"\\newcommand{{\\{tag}ToyLoss}}{{{t['final_loss']:.2e}}}")
    cs = " ".join(f"{c:+.2f}" for c in t["coeffs"])
    L.append(f"\\newcommand{{\\{tag}Coeffs}}{{{cs}}}")

# --- GPT table --------------------------------------------------------------
runs = ROOT.parent / "runs"
gpt_rows = []
for run, name in [("vanilla", "vanilla GPT (no HC)"), ("unimhc", "Uni-mHC (Ours)"),
                  ("givens", "GivensMHC (Ours-Fast)"), ("sinkhorn", "Sinkhorn mHC"),
                  ("ortho", "Orthostochastic")]:
    mf = runs / run / "metrics.jsonl"
    if run == "vanilla" and not mf.exists():
        # nanoGPT train.py logs to stdout only: parse runs/vanilla.log
        vf = runs / "vanilla.log"
        if not vf.exists():
            continue
        final, times = None, []
        for line in vf.read_text().splitlines():
            if line.startswith("step ") and "val loss" in line:
                tr = float(line.split("train loss ")[1].split(",")[0])
                va = float(line.split("val loss ")[1])
                final = (tr, va)
            elif line.startswith("iter "):
                try:
                    times.append(float(line.split("time ")[1].split("ms")[0]))
                except (IndexError, ValueError):
                    pass
        if final is None:
            continue
        ms = sum(times[-50:]) / max(len(times[-50:]), 1)
        gpt_rows.append((name, final[0], final[1], ms))
        continue
    last = None
    for line in mf.read_text().splitlines():
        if line.strip():
            last = json.loads(line)
    if last is None:
        continue
    log = (runs / run / "train_log.txt").read_text().splitlines()
    ms = 0.0
    for ln in log:
        if "ms/iter avg" in ln:
            ms = float(ln.split("ms/iter")[0].split("(")[-1].strip())
    gpt_rows.append((name, last["train"], last["val"], ms))

if gpt_rows:
    best_val = min(r[2] for r in gpt_rows)
    rows = []
    for name, tr, va, ms in gpt_rows:
        va_s = f"\\textbf{{{va:.3f}}}" if va == best_val else f"{va:.3f}"
        rows.append(f"{name} & {tr:.3f} & {va_s} & {ms:.0f} \\\\")
    body = "\n".join(rows)
else:
    body = "(training in progress) & -- & -- & -- \\\\"
L.append(f"\\newcommand{{\\gptTableBody}}{{%\n{body}}}")
L.append(f"\\newcommand{{\\gptRunsCount}}{{{max(len(gpt_rows), 1)}}}")
if gpt_rows:
    best = min(gpt_rows, key=lambda r: r[2])
    L.append(f"\\newcommand{{\\gptBestName}}{{{best[0]}}}")
    L.append(f"\\newcommand{{\\gptBestVal}}{{{best[2]:.3f}}}")

OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(L)} macros, {len(gpt_rows)} GPT rows)")
